export const siteConfig = {
  name: 'Ibim Braide',
  title: 'Ibim Braide | Software Engineer',
  description:
    'Software engineer, community organiser, and open source contributor based in the United Kingdom. Building across frontend, backend, mobile, and data.',
  url: 'https://ibimbraide.dev',
  locale: 'en-GB',
  author: {
    name: 'Ibim Braide',
    email: 'ibimbraide@gmail.com',
    github: 'https://github.com/iclectic',
    linkedin: 'https://www.linkedin.com/in/ibim-braide/',
    twitter: 'https://twitter.com/Tubo_ibim',
  },
  nav: [
    { label: 'Home', href: '/' },
    { label: 'About', href: '/about' },
    { label: 'Projects', href: '/projects' },
    { label: 'Open Source', href: '/open-source' },
    { label: 'Community', href: '/community' },
    { label: 'Writing', href: '/writing' },
    { label: 'Speaking', href: '/speaking' },
    { label: 'Case Studies', href: '/case-studies' },
    { label: 'Contact', href: '/contact' },
  ],
  footerNav: [
    { label: 'Home', href: '/' },
    { label: 'About', href: '/about' },
    { label: 'Projects', href: '/projects' },
    { label: 'Case Studies', href: '/case-studies' },
    { label: 'Open Source', href: '/open-source' },
    { label: 'Writing', href: '/writing' },
    { label: 'Community', href: '/community' },
    { label: 'Speaking', href: '/speaking' },
    { label: 'Now', href: '/now' },
    { label: 'Uses', href: '/uses' },
    { label: 'Media', href: '/media' },
    { label: 'Timeline', href: '/timeline' },
    { label: 'Tech Nation', href: '/tech-nation' },
    { label: 'Contact', href: '/contact' },
    { label: 'CV', href: '/cv' },
  ],
} as const
