import Head from 'next/head'
import Layout from '@/components/Layout'
import Image from 'next/image'
import profilePic from "../../public/images/profile/epiphany.png";
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import TransitionEffect from '@/components/TransitionEffect';





export default function Home() {
  return (
    <>
      <Head>
        <title>Ibim Braide</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className="flex items-center justify-between w-full lg:flex-col"> 
              <div className='w-1/2 md:w-full'>
                <Image src={profilePic} alt="Ibim Braide" className='w-full h-auto lg:hidden md:inline-block md:w-full'
                priority
                sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                50vw"  
                /> 
              </div>
              <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center button-group'>
                <AnimatedText text="A Personal Snapshot" className='!text-6xl !text-left
                xl:!text-5xl lg:!text-center lg:!text=6xl md:!text-5xl sm:!text-3xl
                '/>
                <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                I am an IT Support Specialist with 
                experience in web development. I am 
                passionate about web and mobile development, 
                data analysis, and machine learning. I love 
                cooking and am obsessed with cooking shows 
                and food reviews. I also enjoy reading, and 
                at the moment, I am reading Bad Feminist by 
                Roxane Gay. My favourite films are The Karate 
                Kid, starring Ralph Macchio and Pat Morita 
                (I love an underdog story), and 3 Idiots.
                </p>


                <div className='flex flex-wrap items-center self-start mt-2 lg:self-center justify-center space-x-1 lg:space-x-0 lg:space-y-4 lg:flex-col'>
                <Link href="/curriculum-vitae.pdf" target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 w-40 h-12
                  rounded-lg text-sm font-semibold hover:b-light hover:text-dark
                  border-2 border-solid border-transparent hover:border-dark
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                  hover:dark:border-light"
                  download={true} 
                  >
                      Dev Resume <LinkArrow className={"w-2 ml-1"} />
              </Link>

              <Link href="/curriculum-vitae.pdf" target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 w-40 h-12
                  rounded-lg text-sm font-semibold hover:b-light hover:text-dark
                  border-2 border-solid border-transparent hover:border-dark
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                  hover:dark:border-light"
                  download={true} 
              >
                  Data Analyst Resume <LinkArrow className={"w-2 ml-1"} />
              </Link>


                  <Link href="mailto:ibimbraide@gmail.com" target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base
                  "
                  >Contact</Link> 
                </div>
              </div>
          </div>
        </Layout>

        <HireMe />

      </main>
    </>
  )
}
